package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "JdtJavaToolchainRef",
    srcs = ["JdtJavaBuilder_deploy.jar"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["@//:__pkg__"],
)
