name: Release

on:
  # only manual from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build JdtJavaBuilder_deploy.jar
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build :JdtJavaBuilder_deploy.jar
        cp -fv bazel-bin/JdtJavaBuilder_deploy.jar compiler/export/

    - name: Test Compile
      run: |
        cd examples/
        "${GITHUB_WORKSPACE}/bin/bazel" build //...

    - name: Build Distribution
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //dist:all

    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE
          bazel-bin/dist/rules_jdt-*.tar.gz
          bazel-bin/dist/changelog.txt
          bazel-bin/dist/relnotes.txt
